stages:
  - lint
  - build
  - test
  - package
  - deploy

lint-front:
  image: node:4.2.2
  stage: lint
  script:
    - echo "I'm linting your angular code" 
    - cd webapp
    - npm install eslint --save-dev
    - npx eslint "**/*.ts"
    
