stages:
  - lint
  - build
  - test
  - package
  - deploy

lint-front:
  image: node:15.12.0-alpine3.10
  stage: lint
  script:
    - echo "I'm linting your angular code"
    - ls
    - cd webapp
    - npm install
    - npm install eslint --save-dev
    - npm i npx
    - npx eslint "**/*.ts"

lint-back:
  image: golang:1.10
  stage: lint
  script:
    - echo "I'm linting your go code"
    - cd server
    - export GOPATH=`pwd`
    - echo $GOPATH
    - go get -u golang.org/x/lint/golint
    - ./bin/golint main.go