stages:
  - lint
  - build
  - test
  - package
  - deploy

lint-front:
  stage: lint
  script:
    - echo "I'm linting your angular code"
    - cd webapp
    - npm install
    - npm install eslint --save-dev
    - npm i npx
    - npx eslint "**/*.ts"

lint-back:
  image: golang:1.10
  stage: lint
  script:
    - echo "I'm linting your go code"
    - cd server
    - export GOPATH=`pwd`
    - echo $GOPATH
    - go get -u golang.org/x/lint/golint
    - ./bin/golint files/main.go

build-front:
  stage: build
  script:
    - echo "Hello, i'm building your front-end"
    - cd ./webapp
    - npm install
    - npm install @angular/cli
    - npm run build
    - cp -r dist/ /home/camillep/Documents/GitlabRunner/tmp

build-back:
  image: golang:1.10
  stage: build
  script:
    - echo "Hello, i'm building your back-end"
    - cd server/files
    - go build main.go
    - cp main /home/camillep/Documents/GitlabRunner/tmp

test-front:
  allow_failure: true
  stage: test
  script:
    - echo "I'm testing your front"
    - cd ./webapp
    - npm install
    - npm install @angular/cli
    - npm run test

test-back:
  image: golang:1.10
  allow_failure: true
  stage: test
  script:
    - echo "I'm testing your back"
    - cd server/files
    - go test

package-job:
  stage: package
  script:
    - echo "I'm packaging your code to the staging environment"
    - cp -r /home/camillep/Documents/GitlabRunner/tmp /home/camillep/Documents/CICD/cici-production
  only:
    - master