stages:
  - lint
  - build
  - package
  - test
  - deploy

prepare-front:
  image: node:14
  stage: build
  script:
    - echo "Hello, i'm packaging your front-end"
    - cd ./webapp
    - npm install
    - npm install -g @angular/cli
    - npm run build

prepare-back:
  image: golang:1.10
  stage: build
  script:
    - cd server && go run main.go

build-front:
  stage: build
  script: 
    - cd webapp && ng serve

build-server: 
  stage: build
  script:
    - cd server && ng serve

lint-job:
  stage: lint
  script:
    - echo "Now, i'm linting your application"

test-job: 
  stage: test
  script: 
    - echo "Then, i'm testing your application"

deploy-job:
  stage: deploy
  script:
    - echo "To end, i'm deploying your application"
