stages:
  - lint
  - build
  - test
  - package
  - deploy

default:
  image: node:latest

.before_deploy: &before_deploy_shared
  before_script:
    - apt update
    - apt install git
    # Setup SSH deploy keys
    - which ssh-agent || ( apt install openssh-client )
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS_STAGING" >> ~/.ssh/known_hosts
    - echo "$SSH_KNOWN_HOSTS_PROD" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - export PATH=$PATH:/usr/local/bin


lint-front:
  stage: lint
  script:
    - echo "I'm linting your angular code"
    - cd webapp
    - npm install
    - npm install eslint --save-dev
    - npm i npx
    - npx eslint "**/*.ts"

lint-back:
  image: golang:1.10
  stage: lint
  script:
    - echo "I'm linting your go code"
    - cd server
    - export GOPATH=`pwd`
    - echo $GOPATH
    - go get -u golang.org/x/lint/golint
    - ./bin/golint files/main.go

build-front:
  stage: build
  script:
    - echo "Hello, i'm building your front-end"
    - cd ./webapp
    - npm install
    - npm install @angular/cli
    - npm run build --prod
  artifacts:
    paths:
      - /builds/CamillePolice/cicd-module/webapp/dist/

build-back:
  image: golang:1.10
  stage: build
  script:
    - echo "Hello, i'm building your back-end"
    - cd server/files
    - go build main.go
  artifacts:
    paths:
      - /builds/CamillePolice/cicd-module/server/files/main

test-front:
  allow_failure: true
  stage: test
  script:
    - echo "I'm testing your front"
    - cd ./webapp
    - npm install
    - npm install @angular/cli
    - npm run test

test-back:
  image: golang:1.10
  allow_failure: true
  stage: test
  script:
    - echo "I'm testing your back"
    - cd server/files
    - go test

package-job:
  <<: *before_deploy_shared
  stage: package
  script:
    - echo "I'm packaging your code to the staging environment"
    - apt install lsof
    - scp /builds/CamillePolice/cicd-module/server/files/main tchiquizz@34.105.247.189:/www/staging
    - scp -r /builds/CamillePolice/cicd-module/webapp/dist/webapp tchiquizz@34.105.247.189:/www/staging
    - ssh tchiquizz@34.105.247.189 "systemctl restart nginx ; kill -9 $(lsof -t -i:8090) ; /www/staging/main &"
  only:
    - master

deploy-job:
  <<: *before_deploy_shared
  stage: deploy
  script:
    - echo "I'm deploying your code to the production environment"
    - scp /builds/CamillePolice/cicd-module/server/files/main tchiquizz@35.246.86.197:/www/prod
    - scp -r /builds/CamillePolice/cicd-module/webapp/dist/ tchiquizz@35.246.86.197:/www/prod
    - ssh tchiquizz@35.246.86.197 "sudo systemctl restart nginx ; sudo kill -9 $(sudo lsof -t -i:8090) ; /www/prod/main &"
  tags:
    - tag
