stages:
  - lint
  - build
  - test
  - package
  - deploy

lint-front:
  image: node:6.10.3
  stage: lint
  script:
    - echo "I'm linting your angular code"
    - ls
    - cd webapp
    - npm install eslint --save-dev
    - npm i npx
    - npx eslint "**/*.ts"
    
