image: golang:1.10

stages:
  - package
  - build
  - lint
  - test
  - deploy

package-front:
  stage: package
  script:
    - echo "Hello, i'm packaging your front-end"
    - cd ./webapp
    - apt install npm
    - npm install
    - npm install -g @angular/cli
    - npm run build

package-back:
  stage: package
  script:
     - go get -u github.com/golang/dep/cmd/dep
    - mkdir -p $GOPATH/src
    - cd $GOPATH/src
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME
    - dep ensure

build-front:
  stage: build
  script: 
    - cd webapp && ng serve

build-server: 
  stage: build
  script:
    - cd server && ng serve

lint-job:
  stage: lint
  script:
    - echo "Now, i'm linting your application"

test-job: 
  stage: test
  script: 
    - echo "Then, i'm testing your application"

deploy-job:
  stage: deploy
  script:
    - echo "To end, i'm deploying your application"
