stages:
  - lint
  - build
  - test
  - package
  - deploy

lint-job:
  stage: lint
  script:
    - echo "I'm linting your code"

prepare-front:
  image: node:14
  stage: build
  script:
    - echo "Hello, i'm preparing your front-end"
    - cd ./webapp
    - npm install
    - npm install -g @angular/cli
    - npm run build

